BEGIN TRANSACTION;
DROP TABLE IF EXISTS "referralTitle";
CREATE TABLE IF NOT EXISTS "referralTitle" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "referralBody";
CREATE TABLE IF NOT EXISTS "referralBody" (
	"id"	INTEGER NOT NULL UNIQUE,
	"body"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "subreddit";
CREATE TABLE IF NOT EXISTS "subreddit" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "linkTitleBody";
CREATE TABLE IF NOT EXISTS "linkTitleBody" (
	"idTitle"	INTEGER NOT NULL UNIQUE,
	"idBody"	INTEGER NOT NULL UNIQUE,
	"id"	INTEGER NOT NULL UNIQUE,
	"isTangerine"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idTitle") REFERENCES "referralTitle"("id"),
	FOREIGN KEY("idBody") REFERENCES "referralBody"("id")
);
COMMIT;
